# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'cdotyone'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-ZNT55L44X4'

menu: 
  - name: SpaceX CAMS
    link: /nerdle-dash
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/cdotyone
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/chrisdoty/
      - name: Twitter
        icon: twitter
        link: https://twitter.com/cdotyone
    
